=== JesusPereira-ctrl/curso-java-devtalles/08-json-con-gson/person-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 3,
        "maxLength": 50
      },
      "age": {
        "type": "integer",
        "minimum": 0
      },
      "student": {
        "type": "boolean"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "hobbies": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "age",
      "student",
      "email",
      "hobbies"
    ]
  }
}

=== JesusPereira-ctrl/curso-java-devtalles/08-json-con-gson/person.json
[
  {
    "name": "Fernando",
    "age": 30,
    "student": true,
    "email": "fernando@devtalles.com",
    "hobbies": [
      "Correr",
      "Crear contenido",
      "Estudiar"
    ]
  },
  {
    "name": "Teddy",
    "age": 30,
    "student": true,
    "email": "teddy@devtalles.com",
    "hobbies": [
      "Correr",
      "Caminar",
      "Tenis"
    ]
  }
]
